{{- if .Values.lyrics.nginx.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lyrics.fullname" . }}-nginx
  namespace: {{ .Values.lyrics.namespace }}
  labels:
    app: {{ include "lyrics.fullname" . }}-nginx
spec:
  replicas: {{ .Values.lyrics.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ include "lyrics.fullname" . }}-nginx
  template:
    metadata:
      labels:
        app: {{ include "lyrics.fullname" . }}-nginx
    spec:
      initContainers:
      - name: app-health-check
        image: giantswarm/tiny-tools:3.12
        command: ['sh', '-c', "until curl -I {{ .Release.Name }}-app:{{ .Values.lyrics.port }}/lyrics?song=healthcheck; do echo waiting for app...; sleep 2; done"]
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: {{ .Values.lyrics.nginx.port }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-static
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: nginx-static
        configMap:
          name: nginx-static

{{- end }}
