apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
spec:
  selector:
    app: {{ include "lyrics.fullname" . }}-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.lyrics.port }}
      targetPort: {{ .Values.lyrics.port }}
      nodePort: 30001
