global:
  env: development
  helmDefault: false
  valuesFile: values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL: https://github.com/ronsha001/robust-app-of-apps.git
      targetRevision: HEAD

argocdApplications:
  folder-1:
    lyrics:
      disableAutomated: false
      disableFinalizer: false
      disable: false
      name: lyrics
      namespace: lyrics
      wave: 1
      # targetRevision: HEAD
    my-nginx-app:
      disableAutomated: false
      disableFinalizer: false
      disable: false
      name: my-nginx-app-1
      namespace: nginx-1
      wave: 2
  folder-2:
    my-nginx-app:
      disableAutomated: false
      disableFinalizer: false
      disable: false
      name: my-nginx-app-2
      namespace: nginx-2
      wave: 2
      # targetRevision: HEAD