global:
  env: development
  helmDefault: false
  valuesFile: values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL: https://github.com/ronsha001/robust-app-of-apps.git
      targetRevision: HEAD

argocdApplications:
  lyrics:
    disableAutomated: false
    disableFinalizer: false
    disable: false
    name: lyrics
    namespace: lyrics
    # targetRevision: HEAD
  my-nginx-app:
    disableAutomated: false
    disableFinalizer: false
    disable: false
    name: my-nginx-app
    namespace: nginx-2
    # targetRevision: HEAD
