global:
  env: development
  helmDefault: false
  valuesFile: values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL: https://github.com/ranrubin/argocd-app-of-apps
      targetRevision: HEAD

argocdApplications:
  lyrics:
    disableAutomated: false
    disable: false
    name: lyrics
    namespace: lyrics
    # targetRevision: HEAD
  my-nginx-app:
    disableAutomated: false
    disable: false
    name: nginx-11
    namespace: nginx-1
    # targetRevision: HEAD
