apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  source:
    repoURL: https://github.com/ronsha001/robust-app-of-apps.git
    targetRevision: HEAD
    path: my-nginx-app
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-1

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true