{{- range $app, $appConfig := .Values.argocdApplications -}}
{{- range $folder := $app -}}
{{ if not .disable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}-{{ $.Values.global.env }}
  namespace: argocd
  {{- if not .disableFinalizer }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .wave }}"
spec:
  project: {{ $.Values.global.spec.project }}
  source:
    repoURL:  {{ $.Values.global.spec.source.repoURL }}
    targetRevision: {{ default $.Values.global.spec.source.targetRevision .targetRevision }}
    path: charts/{{ .name }}
    {{- if default $.Values.global.helmDefault .helm }}
    helm:
      valueFiles:
      - {{ $.Values.global.valuesFile }}
    {{- end }}
  destination:
    namespace: {{ default $.Values.global.spec.destination.namespace  .namespace }}
    server: {{ $.Values.global.spec.destination.server }}
  syncPolicy:
    {{- if not .disableAutomated }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
{{- end }}
{{- end }}