apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lyrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/ronsha001/Lyrics-Chart.git
    targetRevision: HEAD
    path: lyrics
  destination:
    server: https://kubernetes.default.svc
    namespace: lyrics

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true